import '@/styles/globals.css'
import { AnimatePresence } from 'motion/react';
import { AppProps } from 'next/app';
import Link from 'next/link';
import Head from 'next/head';
import { AnimatedButton } from '@/components/AnimatedButton';

export default function App({ Component, pageProps, router} : AppProps) {
    return (
        <>
            <Head>
                <title>Owen Sellner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='nav'>
                <div style={{ flexGrow: 1 }}>
                    <Link style={{ fontSize: "24px", fontWeight: 900 }} href="/">OS</Link>
                </div>
                <div style={{ display: "flex" }}>
                    <AnimatedButton text="ABOUT" href="/" />
                    <AnimatedButton text="PROJECTS" href="/projects" />
                    <AnimatedButton text="RESUME" target="_blank" href="/Resume.pdf" />
                </div>
            </div>
            <AnimatePresence mode='wait'>
                <Component key={router.route} {...pageProps} />
            </AnimatePresence>
        </>
    )
}