import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Owen Sellner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <section style={{ height: "80vh", width: "100vw", display: "flex", justifyContent: "center", alignItems: "center" }}>
                    <h1 style={{ fontSize: "120px" }}>OWEN SELLNER</h1>
                </section>
            </main>
        </>
    )
}