import { AnimatedName } from '@/components/AnimatedName'
import { AnimatedSubtitles } from '@/components/AnimatedSubtitles'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Owen Sellner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <section style={{ height: "80vh", width: "100vw", display: "flex", justifyContent: "center", alignItems: "center" }}>
                    <div>
                        <AnimatedName />
                        <AnimatedSubtitles />
                    </div>
                </section>
            </main>
        </>
    )
}